import type { SkillCategory } from '../store/types'

export const DEMO_UNLOCK_ALL = true

export type SkillBranch = 'general' | 'offense' | 'defense'
export type SkillPosition = 'qb' | 'receiver' | 'snapper' | 'rusher' | 'db'
export type SkillTier = 0 | 1 | 2 | 3 | 4 | 5

export type SkillNode = {
  id: string
  name: string
  branch: SkillBranch
  position: SkillPosition | null
  tier: SkillTier
  tierLabel?: string
  description: string
  drill?: string
  masteryCriteria: string
  ruleRef?: string
  prereqs: string[]
  sortOrder: number
  interactive?: boolean
  category?: SkillCategory
  lesson?: { heading: string; bullets: string[] }
  quiz?: Array<{
    id: string
    prompt: string
    choices: string[]
    correctIndex: number
  }>
  drillInteractive?: {
    title: string
    instructions: string
    targetReps: number
  }
}

export const BRANCH_META: Record<
  SkillBranch,
  { id: SkillBranch; name: string; color: string; unlocks: string[] }
> = {
  general: {
    id: 'general',
    name: 'Fondasi',
    color: '#64748b',
    unlocks: ['offense', 'defense'],
  },
  offense: {
    id: 'offense',
    name: 'Offense',
    color: '#2563eb',
    unlocks: ['qb', 'receiver'],
  },
  defense: {
    id: 'defense',
    name: 'Defense',
    color: '#dc2626',
    unlocks: ['rusher', 'db'],
  },
}

export const POSITION_META: Array<{
  id: SkillPosition
  name: string
  branch: SkillBranch
  subBranch?: { id: SkillPosition; name: string }
}> = [
  { id: 'qb', name: 'Quarterback', branch: 'offense' },
  {
    id: 'receiver',
    name: 'Receiver',
    branch: 'offense',
    subBranch: { id: 'snapper', name: 'Snapper' },
  },
  { id: 'rusher', name: 'Pass Rusher', branch: 'defense' },
  { id: 'db', name: 'Defensive Back', branch: 'defense' },
]

export const TIER_LABELS: Record<number, string> = {
  0: 'General',
  1: 'Branch',
  2: 'Foundation',
  3: 'Core',
  4: 'Advanced',
  5: 'Elite',
}

/** Legacy level id → skill id for persist migration */
export const LEGACY_LEVEL_TO_SKILL: Record<number, string> = {
  1: 'GEN-01',
  2: 'GEN-05',
  3: 'GEN-08',
}

export const SKILLS: SkillNode[] = [

  {
    id: 'GEN-01',
    name: 'Aturan Dasar IFAF 5v5',
    branch: 'general',
    position: null,
    tier: 0,
    description: `5 pemain, 4 down ke garis tengah, tidak ada tendangan, TD 6 / try 1-2, no-run zone`,
    drill: `Kuis 20 soal + tonton 1 pertandingan sambil menyebut down & distance`,
    masteryCriteria: `Skor kuis ≥18/20 dan benar menyebut down & distance 10 play berturut-turut`,
    prereqs: [],
    sortOrder: 0,
    interactive: true,
    category: 'Rules',
    lesson: {
      heading: 'Lapangan & aturan non-kontak',
      bullets: [
      'Flag football 5v5 IFAF: tidak ada tackling, blocking, atau kontak sengaja. Cabut flag lawan untuk menghentikan play.',
      'Field of play 50 yard x 25 yard, plus endzone 10 yard di tiap ujung.',
      'Middle line membagi lapangan. Line to gain pertama = middle, bukan "1st & 10".',
      'No-running zone: 5 yard di depan tiap goal line. Di zona ini offense wajib forward pass.',
      'Skor dasar: touchdown 6, try 1 (dari yard 5) atau 2 (dari yard 10). Safety 2.',
      ],
    },
    quiz: [
    {
      id: 'gen01q1',
      prompt: 'Apa line to gain pada seri down pertama (sisi sendiri)?',
      choices: ['10 yard ke depan', 'Middle', 'Goal line lawan', 'Scrimmage line'],
      correctIndex: 1,
    },
    {
      id: 'gen01q2',
      prompt: 'Di no-running zone, offense harus...',
      choices: ['Boleh run play bebas', 'Wajib forward pass play', 'Punt bola', 'Ganti ke defense'],
      correctIndex: 1,
    },
    {
      id: 'gen01q3',
      prompt: 'Bagaimana cara menghentikan ball carrier di flag football?',
      choices: ['Tackle ke tanah', 'Block dengan bahu', 'Cabut (pull) flag-nya', 'Dorong keluar lapangan saja'],
      correctIndex: 2,
    }
    ],
    drillInteractive: {
      title: 'Zone walk',
      instructions: `Berjalan di lapangan (atau di rumah dengan zona imajiner). Sebut keras tiap zona yang kamu masuki: endzone, middle, no-running zone. Target 5 reps.`,
      targetReps: 5,
    },
  },
  {
    id: 'GEN-02',
    name: 'Sikap Atletik',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Lutut tertekuk, berat di ujung kaki, tangan siap, pandangan ke depan`,
    drill: `Tahan sikap 30 detik, reaksi ke arah acak`,
    masteryCriteria: `Tetap seimbang saat didorong ringan dari 4 arah`,
    prereqs: [],
    sortOrder: 1,
  },
  {
    id: 'GEN-03',
    name: 'Akselerasi & Perubahan Arah',
    branch: 'general',
    position: null,
    tier: 0,
    description: `3 langkah pertama, menurunkan pinggul saat memotong`,
    drill: `Pro agility 5-10-5, cone L-drill`,
    masteryCriteria: `5-10-5 di bawah 5.5 detik, tanpa melebar saat memotong`,
    prereqs: [],
    sortOrder: 2,
  },
  {
    id: 'GEN-04',
    name: 'Pemasangan Flag yang Benar',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Sabuk pas di pinggang, flag menggantung bebas di kedua sisi, tidak tertutup baju`,
    drill: `Cek sabuk berpasangan sebelum tiap latihan`,
    masteryCriteria: `Flag tidak pernah lepas sendiri dalam 1 sesi penuh`,
    prereqs: [],
    sortOrder: 3,
  },
  {
    id: 'GEN-05',
    name: 'Deflag Dasar',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Dua tangan, target pinggang bukan badan, ambil sudut ke depan runner`,
    drill: `Deflag berpasangan kecepatan 50% → 100%`,
    masteryCriteria: `8 dari 10 deflag berhasil pada percobaan pertama`,
    prereqs: [],
    sortOrder: 4,
    interactive: true,
    category: 'Movement',
    lesson: {
      heading: 'Gerakan tanpa tackling',
      bullets: [
      'Flag belt dipakai di pinggang; dua flag di samping. Pull salah satu flag untuk menghentikan play.',
      'Approach dari samping atau depan dengan kaki ringan. Jangan dive atau wrap tubuh.',
      'Setelah pull, angkat flag tinggi agar wasit jelas melihat. Jangan lempar jauh.',
      'Sebagai ball carrier: lindungi flag dengan sudut tubuh, tapi jangan cover flag dengan tangan (flag guarding).',
      'Break & plant: ubah arah cepat tanpa kontak tubuh lawan.',
      ],
    },
    quiz: [
    {
      id: 'gen05q1',
      prompt: 'Setelah berhasil flag pull, apa yang sebaiknya dilakukan?',
      choices: ['Lempar flag ke sideline', 'Angkat flag tinggi agar terlihat wasit', 'Tarik belt lawan terus', 'Dorong pemain ke tanah'],
      correctIndex: 1,
    },
    {
      id: 'gen05q2',
      prompt: 'Menutupi flag dengan tangan disebut...',
      choices: ['Fair catch', 'Flag guarding', 'Holding', 'Blitz'],
      correctIndex: 1,
    },
    {
      id: 'gen05q3',
      prompt: 'Cara legal menghentikan runner adalah...',
      choices: ['Wrap tackle', 'Shoulder check', 'Pull salah satu flag', 'Trip kaki'],
      correctIndex: 2,
    }
    ],
    drillInteractive: {
      title: 'Flag pull',
      instructions: `Pasangkan belt (atau imitasikan). Latih approach + pull cepat 10 kali. Catat reps yang bersih tanpa kontak berlebih.`,
      targetReps: 10,
    },
  },
  {
    id: 'GEN-06',
    name: 'Menangkap Bola',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Berlian untuk bola tinggi, kelingking rapat untuk bola rendah, mata ikuti sampai masuk tangan`,
    drill: `50 tangkapan diam, 50 sambil lari`,
    masteryCriteria: `45/50 diam, 40/50 sambil lari`,
    prereqs: [],
    sortOrder: 5,
  },
  {
    id: 'GEN-07',
    name: 'Melempar Dasar',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Grip di jahitan, langkah menyilang, follow-through ke bawah`,
    drill: `30 lemparan 10 yd berpasangan`,
    masteryCriteria: `25/30 spiral, sampai ke dada penerima`,
    prereqs: [],
    sortOrder: 6,
  },
  {
    id: 'GEN-08',
    name: 'Kesadaran Situasi',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Selalu tahu: down keberapa, target middle/goal, posisi bola, sisa waktu, sisa timeout`,
    drill: `Pelatih berteriak "situasi?" acak saat latihan`,
    masteryCriteria: `Jawab benar 10 kali berturut-turut tanpa jeda`,
    prereqs: [],
    sortOrder: 7,
    interactive: true,
    category: 'Strategy',
    lesson: {
      heading: '4 downs & line to gain = middle',
      bullets: [
      'Setiap seri: maksimal 4 down. Tidak ada first down karena yardage tetap. Seri baru muncul setelah melewati middle (sekali) atau menuju goal.',
      'Mulai dari yard 5 sendiri: target pertama = middle. Setelah melewati middle, dapat 4 down baru menuju goal line.',
      'Melewati middle dua kali dalam satu seri tidak memberi first down lagi.',
      'Gagal di down ke-4: lawan mulai dari yard 5 mereka (bukan spot bola mati).',
      'Panggil situasi dengan jelas: "2nd & Middle", "1st & Goal". Hindari format "2nd & 7".',
      ],
    },
    quiz: [
    {
      id: 'gen08q1',
      prompt: 'Setelah offense melewati middle pertama kali, mereka mendapat...',
      choices: ['1 down ekstra saja', '4 down baru menuju goal', 'Field goal otomatis', 'Harus punt'],
      correctIndex: 1,
    },
    {
      id: 'gen08q2',
      prompt: 'Tampilan down yang benar di flag football adalah...',
      choices: ['2nd & 7', '2nd & Middle', '2nd & 10 yards', '2nd down only'],
      correctIndex: 1,
    },
    {
      id: 'gen08q3',
      prompt: 'Jika gagal di 4th down sebelum middle, defense mulai dari...',
      choices: ['Spot bola mati', 'Yard 5 sendiri', 'Middle', 'Endzone'],
      correctIndex: 1,
    }
    ],
    drillInteractive: {
      title: 'Down call',
      instructions: `Sebut keras 8 situasi down (contoh: 1st & Middle, 3rd & Goal, 4th & Middle). Bayangkan posisi bola relatif ke middle.`,
      targetReps: 8,
    },
  },
  {
    id: 'GEN-09',
    name: 'Kondisi Fisik 40 Menit',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Daya tahan interval — flag football adalah sprint berulang, bukan lari jauh`,
    drill: `10×40 yd sprint, istirahat 30 detik`,
    masteryCriteria: `Sprint ke-10 tidak lebih lambat 10% dari sprint pertama`,
    prereqs: [],
    sortOrder: 8,
  },
  {
    id: 'GEN-10',
    name: 'Komunikasi & Sportivitas',
    branch: 'general',
    position: null,
    tier: 0,
    description: `Huddle, sinyal, kembalikan flag ke lawan (tidak melakukannya = penalti 10 yard)`,
    drill: `Simulasi huddle 15 detik, latihan mengembalikan flag`,
    masteryCriteria: `Nol penalti unsportsmanlike dalam 3 pertandingan`,
    prereqs: [],
    sortOrder: 9,
  },
  {
    id: 'OFF-01',
    name: 'Formasi Dasar',
    branch: 'offense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Spread, Trips, Twins, Bunch, Stack, Empty — bisa berbaris benar dalam 5 detik`,
    masteryCriteria: `Berbaris benar di 6 formasi dari panggilan suara, tanpa ragu`,
    prereqs: [],
    sortOrder: 10,
  },
  {
    id: 'OFF-02',
    name: 'Route Tree 0–9',
    branch: 'offense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Hitch, flat, slant, comeback, curl, out, in, corner, post, go`,
    masteryCriteria: `Jalankan 10 route dari panggilan nomor, kedalaman meleset ≤1 yard`,
    prereqs: [],
    sortOrder: 11,
  },
  {
    id: 'OFF-03',
    name: 'Timing & Spacing',
    branch: 'offense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Kenapa batas 7 detik mengubah segalanya; jarak minimal antar receiver`,
    masteryCriteria: `Jelaskan mengapa route >12 yd tidak bisa jadi read pertama`,
    prereqs: [],
    sortOrder: 12,
  },
  {
    id: 'OFF-04',
    name: 'Snap & Alignment',
    branch: 'offense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Snap legal (sumbu bola tegak lurus SL, gerakan mundur menerus), semua pemain di belakang SL`,
    masteryCriteria: `20 snap berturut-turut tanpa penalti false start / illegal snap`,
    prereqs: [],
    sortOrder: 13,
  },
  {
    id: 'OFF-05',
    name: 'Membaca Coverage Pre-Snap',
    branch: 'offense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Man vs zone: jarak defender, arah pandangan mata, ada/tidaknya safety tengah`,
    masteryCriteria: `Identifikasi benar 8 dari 10 gambar coverage`,
    prereqs: [],
    sortOrder: 14,
  },
  {
    id: 'OFF-06',
    name: 'Aturan Offense Kritis',
    branch: 'offense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `QB tidak boleh lewat SL · satu forward pass per down · wajib pass di no-run zone · shielding = penalti · flag guarding = penalti + loss of down`,
    masteryCriteria: `Nol penalti offense akibat kekeliruan aturan dalam 3 pertandingan`,
    prereqs: [],
    sortOrder: 15,
  },
  {
    id: 'DEF-01',
    name: 'Skema Dasar',
    branch: 'defense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `3-2 Zone, 2-2 Box, 1-3-1, Man + Free Rush, Cover 0`,
    masteryCriteria: `Berbaris benar di 5 skema dari panggilan, dalam 5 detik`,
    prereqs: [],
    sortOrder: 16,
  },
  {
    id: 'DEF-02',
    name: 'Sudut Kejar & Leverage',
    branch: 'defense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Kejar ke titik di depan runner, bukan posisi sekarang; jaga bantuan di dalam/luar`,
    masteryCriteria: `9 dari 10 kejaran memotong runner, bukan mengejar dari belakang`,
    prereqs: [],
    sortOrder: 17,
  },
  {
    id: 'DEF-03',
    name: 'Teknik Deflag Lanjutan',
    branch: 'defense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Dua tangan, jangan meraih ke belakang, jangan menerjang badan`,
    masteryCriteria: `8/10 deflag berhasil pada runner kecepatan penuh, nol kontak ilegal`,
    prereqs: [],
    sortOrder: 18,
  },
  {
    id: 'DEF-04',
    name: 'Aturan Blitz',
    branch: 'defense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Mulai >7 yard, satu tangan diangkat minimal 1 detik sebelum snap, maks 2 blitzer, rush lurus & cepat`,
    masteryCriteria: `20 blitz berturut-turut tanpa penalti illegal signal / illegal rush`,
    prereqs: [],
    sortOrder: 19,
  },
  {
    id: 'DEF-05',
    name: 'Komunikasi Defensif',
    branch: 'defense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Panggil coverage, umumkan formasi lawan, pass off receiver di zone`,
    masteryCriteria: `Panggilan terdengar dan benar di 10 snap berturut-turut`,
    prereqs: [],
    sortOrder: 20,
  },
  {
    id: 'DEF-06',
    name: 'Penalti Defensif yang Harus Dihindari',
    branch: 'defense',
    position: null,
    tier: 1,
    tierLabel: 'Branch',
    description: `Illegal flag pull (5 yd) · pass interference (10 yd + otomatis first down) · illegal contact (10 yd + first down) · offside`,
    masteryCriteria: `Nol penalti defensif dalam 2 pertandingan`,
    prereqs: [],
    sortOrder: 21,
  },
  {
    id: 'QB-F1',
    name: 'Grip & Mekanik Spiral',
    branch: 'offense',
    position: 'qb',
    tier: 2,
    tierLabel: 'Foundation',
    description: `40 lemparan 10 yd, fokus follow-through`,
    drill: `40 lemparan 10 yd, fokus follow-through`,
    masteryCriteria: `35/40 spiral rapat, akurat ke dada`,
    prereqs: [],
    sortOrder: 22,
  },
  {
    id: 'QB-F2',
    name: 'Footwork Pasca-Snap',
    branch: 'offense',
    position: 'qb',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Drop 3 langkah, selalu di belakang SL — QB tidak boleh melewatinya`,
    drill: `Drop 3 langkah, selalu di belakang SL — QB tidak boleh melewatinya`,
    masteryCriteria: `20 drop berturut-turut, kaki tidak pernah melewati SL`,
    prereqs: [],
    sortOrder: 23,
  },
  {
    id: 'QB-F3',
    name: 'Akurasi Jarak Dekat (0–7 yd)',
    branch: 'offense',
    position: 'qb',
    tier: 2,
    tierLabel: 'Foundation',
    description: `30 lemparan ke sasaran diam di 5 yd`,
    drill: `30 lemparan ke sasaran diam di 5 yd`,
    masteryCriteria: `26/30 dalam radius 1 yard dari sasaran`,
    prereqs: [],
    sortOrder: 24,
  },
  {
    id: 'QB-F4',
    name: 'Jam Internal 7 Detik',
    branch: 'offense',
    position: 'qb',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Latihan dengan stopwatch keras-keras, sadari kapan detik ke-5`,
    drill: `Latihan dengan stopwatch keras-keras, sadari kapan detik ke-5`,
    masteryCriteria: `Melempar/hand-off sebelum 5 detik di 18 dari 20 snap`,
    prereqs: [],
    sortOrder: 25,
  },
  {
    id: 'QB-C1',
    name: 'Progresi 2 Read + Checkdown',
    branch: 'offense',
    position: 'qb',
    tier: 3,
    tierLabel: 'Core',
    description: `Play mesh: crosser 1 → crosser 2 → snapper`,
    drill: `Play mesh: crosser 1 → crosser 2 → snapper`,
    masteryCriteria: `8/10 memilih target yang benar-benar paling terbuka`,
    prereqs: [],
    sortOrder: 26,
  },
  {
    id: 'QB-C2',
    name: 'Membaca Coverage Pasca-Snap',
    branch: 'offense',
    position: 'qb',
    tier: 3,
    tierLabel: 'Core',
    description: `Konfirmasi man/zone dalam 1 detik setelah snap`,
    drill: `Konfirmasi man/zone dalam 1 detik setelah snap`,
    masteryCriteria: `8/10 identifikasi benar sambil menjalankan drop`,
    prereqs: [],
    sortOrder: 27,
  },
  {
    id: 'QB-C3',
    name: 'Akurasi Menengah 8–15 yd',
    branch: 'offense',
    position: 'qb',
    tier: 3,
    tierLabel: 'Core',
    description: `30 lemparan out & dig ke receiver bergerak`,
    drill: `30 lemparan out & dig ke receiver bergerak`,
    masteryCriteria: `22/30 tepat waktu, di sisi jauh dari defender`,
    prereqs: [],
    sortOrder: 28,
  },
  {
    id: 'QB-C4',
    name: 'Hot Read Anti-Blitz',
    branch: 'offense',
    position: 'qb',
    tier: 3,
    tierLabel: 'Core',
    description: `Lihat 2 tangan terangkat pre-snap → langsung ganti ke slant/flat`,
    drill: `Lihat 2 tangan terangkat pre-snap → langsung ganti ke slant/flat`,
    masteryCriteria: `9/10 mengenali blitz dan melepas bola ≤2.5 detik`,
    prereqs: [],
    sortOrder: 29,
  },
  {
    id: 'QB-C5',
    name: 'Rollout Lateral Legal',
    branch: 'offense',
    position: 'qb',
    tier: 3,
    tierLabel: 'Core',
    description: `Bergerak menyamping di belakang SL untuk mengubah sudut lempar`,
    drill: `Bergerak menyamping di belakang SL untuk mengubah sudut lempar`,
    masteryCriteria: `15 rollout tanpa sekalipun melewati SL`,
    prereqs: [],
    sortOrder: 30,
  },
  {
    id: 'QB-C6',
    name: 'Ball Placement',
    branch: 'offense',
    position: 'qb',
    tier: 3,
    tierLabel: 'Core',
    description: `Bola ke sisi yang jauh dari defender, bukan sekadar "ke arah receiver"`,
    drill: `Bola ke sisi yang jauh dari defender, bukan sekadar "ke arah receiver"`,
    masteryCriteria: `Pelatih menilai 8/10 penempatan aman`,
    prereqs: [],
    sortOrder: 31,
  },
  {
    id: 'QB-A1',
    name: 'Lemparan Antisipasi',
    branch: 'offense',
    position: 'qb',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Melempar sebelum receiver memotong`,
    drill: `Melempar sebelum receiver memotong`,
    masteryCriteria: `7/10 komplet pada route out & comeback`,
    prereqs: [],
    sortOrder: 32,
  },
  {
    id: 'QB-A2',
    name: 'Touch vs Velocity',
    branch: 'offense',
    position: 'qb',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Fade lembut, seam keras, back-shoulder`,
    drill: `Fade lembut, seam keras, back-shoulder`,
    masteryCriteria: `Menunjukkan 3 jenis lemparan berbeda pada situasi yang tepat`,
    prereqs: [],
    sortOrder: 33,
  },
  {
    id: 'QB-A3',
    name: 'Manipulasi Safety',
    branch: 'offense',
    position: 'qb',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Menggeser safety dengan arah mata & bahu sebelum melempar`,
    drill: `Menggeser safety dengan arah mata & bahu sebelum melempar`,
    masteryCriteria: `Rekaman video menunjukkan safety bergeser di 6/10 snap`,
    prereqs: [],
    sortOrder: 34,
  },
  {
    id: 'QB-A4',
    name: 'Manajemen Jam & 2 Menit',
    branch: 'offense',
    position: 'qb',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Tahu kapan jam berhenti (first down, out of bounds, pass jatuh di 2 menit terakhir)`,
    drill: `Tahu kapan jam berhenti (first down, out of bounds, pass jatuh di 2 menit terakhir)`,
    masteryCriteria: `Menjalankan drive 2 menit tanpa membuang timeout sia-sia`,
    prereqs: [],
    sortOrder: 35,
  },
  {
    id: 'QB-A5',
    name: 'Eksekusi No-Run Zone',
    branch: 'offense',
    position: 'qb',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Wajib pass, lapangan sempit, timing sangat ketat`,
    drill: `Wajib pass, lapangan sempit, timing sangat ketat`,
    masteryCriteria: `Konversi 6/10 percobaan dari yard 5`,
    prereqs: [],
    sortOrder: 36,
  },
  {
    id: 'QB-A6',
    name: 'Mengenali Skema dari Pergerakan Awal',
    branch: 'offense',
    position: 'qb',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Membedakan 3-2 zone, 1-3-1, dan man dalam 2 detik pre-snap`,
    drill: `Membedakan 3-2 zone, 1-3-1, dan man dalam 2 detik pre-snap`,
    masteryCriteria: `8/10 benar, diuji dengan video`,
    prereqs: [],
    sortOrder: 37,
  },
  {
    id: 'QB-E1',
    name: 'Audible & Penyesuaian Pre-Snap',
    branch: 'offense',
    position: 'qb',
    tier: 5,
    tierLabel: 'Elite',
    description: `Mengubah play berdasarkan coverage, 5/10 perubahan menghasilkan first down`,
    masteryCriteria: `Mengubah play berdasarkan coverage, 5/10 perubahan menghasilkan first down`,
    prereqs: [],
    sortOrder: 38,
  },
  {
    id: 'QB-E2',
    name: 'Mengendalikan Tempo',
    branch: 'offense',
    position: 'qb',
    tier: 5,
    tierLabel: 'Elite',
    description: `Sengaja mempercepat/melambatkan tempo sesuai kebutuhan skor & jam`,
    masteryCriteria: `Sengaja mempercepat/melambatkan tempo sesuai kebutuhan skor & jam`,
    prereqs: [],
    sortOrder: 39,
  },
  {
    id: 'QB-E3',
    name: 'Keputusan 4th Down',
    branch: 'offense',
    position: 'qb',
    tier: 5,
    tierLabel: 'Elite',
    description: `Tidak ada punt — tiap 4th down keputusan. Rasio konversi ≥50% dalam satu musim`,
    masteryCriteria: `Tidak ada punt — tiap 4th down keputusan. Rasio konversi ≥50% dalam satu musim`,
    prereqs: [],
    sortOrder: 40,
  },
  {
    id: 'WR-F1',
    name: 'Stance & Release Bersih',
    branch: 'offense',
    position: 'receiver',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Keluar dari garis tanpa ragu, langkah pertama ke arah route`,
    drill: `Keluar dari garis tanpa ragu, langkah pertama ke arah route`,
    masteryCriteria: `20 release tanpa langkah palsu`,
    prereqs: [],
    sortOrder: 41,
  },
  {
    id: 'WR-F2',
    name: 'Tangkapan Tinggi / Rendah / Jauh',
    branch: 'offense',
    position: 'receiver',
    tier: 2,
    tierLabel: 'Foundation',
    description: `20 tangkapan tiap jenis`,
    drill: `20 tangkapan tiap jenis`,
    masteryCriteria: `17/20 tiap kategori`,
    prereqs: [],
    sortOrder: 42,
  },
  {
    id: 'WR-F3',
    name: 'Kedalaman Route yang Tepat',
    branch: 'offense',
    position: 'receiver',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Hitung langkah, bukan perasaan`,
    drill: `Hitung langkah, bukan perasaan`,
    masteryCriteria: `10 route berbeda, meleset ≤1 yard`,
    prereqs: [],
    sortOrder: 43,
  },
  {
    id: 'WR-F4',
    name: 'Menangkap Sambil Lari Penuh',
    branch: 'offense',
    position: 'receiver',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Bola dilempar ke depan, tangkap tanpa melambat`,
    drill: `Bola dilempar ke depan, tangkap tanpa melambat`,
    masteryCriteria: `15/20 tanpa mengurangi kecepatan`,
    prereqs: [],
    sortOrder: 44,
  },
  {
    id: 'WR-C1',
    name: 'Ketajaman Cut',
    branch: 'offense',
    position: 'receiver',
    tier: 3,
    tierLabel: 'Core',
    description: `Turunkan pinggul, 1 langkah plant, tanpa melebar`,
    drill: `Turunkan pinggul, 1 langkah plant, tanpa melebar`,
    masteryCriteria: `Cut selesai dalam 1 langkah di 8/10 percobaan`,
    prereqs: [],
    sortOrder: 45,
  },
  {
    id: 'WR-C2',
    name: 'Pemisahan Tanpa Kontak',
    branch: 'offense',
    position: 'receiver',
    tier: 3,
    tierLabel: 'Core',
    description: `Shielding = penalti 5 yard. Pisah lewat kecepatan, tempo, dan fake — bukan badan`,
    drill: `Shielding = penalti 5 yard. Pisah lewat kecepatan, tempo, dan fake — bukan badan`,
    masteryCriteria: `10 route melawan man, nol penalti shielding`,
    prereqs: [],
    sortOrder: 46,
  },
  {
    id: 'WR-C3',
    name: 'Membaca Coverage Saat Berlari',
    branch: 'offense',
    position: 'receiver',
    tier: 3,
    tierLabel: 'Core',
    description: `Man → lari terus. Zone → duduk di celah`,
    drill: `Man → lari terus. Zone → duduk di celah`,
    masteryCriteria: `8/10 penyesuaian benar`,
    prereqs: [],
    sortOrder: 47,
  },
  {
    id: 'WR-C4',
    name: 'Tangkapan Kontes',
    branch: 'offense',
    position: 'receiver',
    tier: 3,
    tierLabel: 'Core',
    description: `Tangan tinggi, mata tetap di bola meski ada defender`,
    drill: `Tangan tinggi, mata tetap di bola meski ada defender`,
    masteryCriteria: `12/20 tangkapan dalam kondisi diganggu`,
    prereqs: [],
    sortOrder: 48,
  },
  {
    id: 'WR-C5',
    name: 'Kesadaran Sideline',
    branch: 'offense',
    position: 'receiver',
    tier: 3,
    tierLabel: 'Core',
    description: `Satu kaki di dalam; sengaja keluar untuk menghentikan jam`,
    drill: `Satu kaki di dalam; sengaja keluar untuk menghentikan jam`,
    masteryCriteria: `8/10 tangkapan sideline dinyatakan sah`,
    prereqs: [],
    sortOrder: 49,
  },
  {
    id: 'WR-C6',
    name: 'Menghindari Flag Guarding',
    branch: 'offense',
    position: 'receiver',
    tier: 3,
    tierLabel: 'Core',
    description: `Tidak menutupi flag dengan tangan/bola/badan — penalti + loss of down`,
    drill: `Tidak menutupi flag dengan tangan/bola/badan — penalti + loss of down`,
    masteryCriteria: `Nol penalti flag guarding dalam 3 pertandingan`,
    prereqs: [],
    sortOrder: 50,
  },
  {
    id: 'WR-A1',
    name: 'Double Move',
    branch: 'offense',
    position: 'receiver',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Sluggo, post-corner, whip`,
    drill: `Sluggo, post-corner, whip`,
    masteryCriteria: `3 double move meyakinkan, defender tertipu ≥5/10`,
    prereqs: [],
    sortOrder: 51,
  },
  {
    id: 'WR-A2',
    name: 'YAC & Menghindari Deflag',
    branch: 'offense',
    position: 'receiver',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Setelah tangkap: potong, bukan lari lurus ke defender`,
    drill: `Setelah tangkap: potong, bukan lari lurus ke defender`,
    masteryCriteria: `Rata-rata ≥3 yard setelah tangkapan`,
    prereqs: [],
    sortOrder: 52,
  },
  {
    id: 'WR-A3',
    name: 'Route dari Stack & Bunch',
    branch: 'offense',
    position: 'receiver',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Timing keluar dari tumpukan tanpa bertabrakan dengan rekan`,
    drill: `Timing keluar dari tumpukan tanpa bertabrakan dengan rekan`,
    masteryCriteria: `10 snap dari bunch tanpa tabrakan dan tanpa penalti`,
    prereqs: [],
    sortOrder: 53,
  },
  {
    id: 'WR-A4',
    name: 'Tempo Route',
    branch: 'offense',
    position: 'receiver',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Lambat lalu cepat untuk memancing defender`,
    drill: `Lambat lalu cepat untuk memancing defender`,
    masteryCriteria: `Perubahan tempo terlihat jelas di video, defender salah langkah 6/10`,
    prereqs: [],
    sortOrder: 54,
  },
  {
    id: 'WR-A5',
    name: 'Menyerang Leverage Defender',
    branch: 'offense',
    position: 'receiver',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Kalau defender di dalam, serang ke luar — dan sebaliknya`,
    drill: `Kalau defender di dalam, serang ke luar — dan sebaliknya`,
    masteryCriteria: `8/10 memilih arah yang benar`,
    prereqs: [],
    sortOrder: 55,
  },
  {
    id: 'WR-E1',
    name: 'Option / Choice Route',
    branch: 'offense',
    position: 'receiver',
    tier: 5,
    tierLabel: 'Elite',
    description: `Sinkron penuh dengan QB — 8/10 membaca defender dengan keputusan yang sama dengan QB`,
    masteryCriteria: `Sinkron penuh dengan QB — 8/10 membaca defender dengan keputusan yang sama dengan QB`,
    prereqs: [],
    sortOrder: 56,
  },
  {
    id: 'WR-E2',
    name: 'Route No-Run Zone',
    branch: 'offense',
    position: 'receiver',
    tier: 5,
    tierLabel: 'Elite',
    description: `Fade, back-shoulder, slant cepat di ruang sempit — konversi ≥50%`,
    masteryCriteria: `Fade, back-shoulder, slant cepat di ruang sempit — konversi ≥50%`,
    prereqs: [],
    sortOrder: 57,
  },
  {
    id: 'SNP-1',
    name: 'Snap Legal & Konsisten',
    branch: 'offense',
    position: 'snapper',
    tier: 2,
    tierLabel: 'Foundation',
    description: `25 snap berturut-turut ke tangan QB tanpa penalti`,
    masteryCriteria: `25 snap berturut-turut ke tangan QB tanpa penalti`,
    prereqs: [],
    sortOrder: 58,
  },
  {
    id: 'SNP-2',
    name: 'Release Cepat Pasca-Snap',
    branch: 'offense',
    position: 'snapper',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Masuk ke flat/checkdown dalam 1.5 detik setelah snap`,
    masteryCriteria: `Masuk ke flat/checkdown dalam 1.5 detik setelah snap`,
    prereqs: [],
    sortOrder: 59,
  },
  {
    id: 'SNP-3',
    name: 'Checkdown yang Bisa Diandalkan',
    branch: 'offense',
    position: 'snapper',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Selalu berada di penglihatan QB pada detik ke-4, tangkap 9/10`,
    masteryCriteria: `Selalu berada di penglihatan QB pada detik ke-4, tangkap 9/10`,
    prereqs: [],
    sortOrder: 60,
  },
  {
    id: 'RSH-F1',
    name: 'Aturan Blitz IFAF',
    branch: 'defense',
    position: 'rusher',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Mulai >7 yd · satu tangan diangkat ≥1 detik sebelum snap · maks 2 blitzer · rush harus cepat dan lurus ke titik QB`,
    drill: `Mulai >7 yd · satu tangan diangkat ≥1 detik sebelum snap · maks 2 blitzer · rush harus cepat dan lurus ke titik QB`,
    masteryCriteria: `20 blitz tanpa penalti illegal signal`,
    prereqs: [],
    sortOrder: 61,
  },
  {
    id: 'RSH-F2',
    name: 'Start Eksplosif dari 7 Yard',
    branch: 'defense',
    position: 'rusher',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Sprint 7 yard dari sikap siap`,
    drill: `Sprint 7 yard dari sikap siap`,
    masteryCriteria: `Menempuh 7 yard dalam ≤1.4 detik`,
    prereqs: [],
    sortOrder: 62,
  },
  {
    id: 'RSH-F3',
    name: 'Jalur Lurus ke Titik QB',
    branch: 'defense',
    position: 'rusher',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Belok atau melambat = kehilangan right of way`,
    drill: `Belok atau melambat = kehilangan right of way`,
    masteryCriteria: `10 rush berturut-turut, jalur lurus, dinilai video`,
    prereqs: [],
    sortOrder: 63,
  },
  {
    id: 'RSH-C1',
    name: 'Timing Snap',
    branch: 'defense',
    position: 'rusher',
    tier: 3,
    tierLabel: 'Core',
    description: `Baca tangan snapper, bukan bola`,
    drill: `Baca tangan snapper, bukan bola`,
    masteryCriteria: `Nol offside dalam 20 snap, waktu reaksi ≤0.3 detik`,
    prereqs: [],
    sortOrder: 64,
  },
  {
    id: 'RSH-C2',
    name: 'Menghindari Kontak',
    branch: 'defense',
    position: 'rusher',
    tier: 3,
    tierLabel: 'Core',
    description: `Illegal contact = 10 yard + otomatis first down. Rush melewati, bukan menembus`,
    drill: `Illegal contact = 10 yard + otomatis first down. Rush melewati, bukan menembus`,
    masteryCriteria: `Nol penalti kontak dalam 3 pertandingan`,
    prereqs: [],
    sortOrder: 65,
  },
  {
    id: 'RSH-C3',
    name: 'Deflag QB (Sack)',
    branch: 'defense',
    position: 'rusher',
    tier: 3,
    tierLabel: 'Core',
    description: `Sudut mendekat, tangan ke pinggang, jangan meraih ke atas`,
    drill: `Sudut mendekat, tangan ke pinggang, jangan meraih ke atas`,
    masteryCriteria: `6/10 sack pada QB yang menahan bola >4 detik`,
    prereqs: [],
    sortOrder: 66,
  },
  {
    id: 'RSH-C4',
    name: 'Contain Rollout Lateral',
    branch: 'defense',
    position: 'rusher',
    tier: 3,
    tierLabel: 'Core',
    description: `QB tidak boleh lewat SL, tapi boleh geser menyamping — potong jalurnya`,
    drill: `QB tidak boleh lewat SL, tapi boleh geser menyamping — potong jalurnya`,
    masteryCriteria: `QB tidak berhasil geser >5 yard di 8/10 rush`,
    prereqs: [],
    sortOrder: 67,
  },
  {
    id: 'RSH-C5',
    name: 'Mempertahankan Right of Way',
    branch: 'defense',
    position: 'rusher',
    tier: 3,
    tierLabel: 'Core',
    description: `Rush terus meski QB bergerak — melambat = hilang hak jalan`,
    drill: `Rush terus meski QB bergerak — melambat = hilang hak jalan`,
    masteryCriteria: `Dinilai wasit/pelatih: 9/10 rush sah`,
    prereqs: [],
    sortOrder: 68,
  },
  {
    id: 'RSH-A1',
    name: 'Koordinasi 2 Blitzer',
    branch: 'defense',
    position: 'rusher',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Dua jalur yang tidak bertabrakan, satu contain satu tekan — 8/10 rush terkoordinasi`,
    masteryCriteria: `Dua jalur yang tidak bertabrakan, satu contain satu tekan — 8/10 rush terkoordinasi`,
    prereqs: [],
    sortOrder: 69,
  },
  {
    id: 'RSH-A2',
    name: 'Membaca Handoff & Fake',
    branch: 'defense',
    position: 'rusher',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Tidak termakan fake, tetap ke QB kalau bola masih di tangannya — 8/10 benar`,
    masteryCriteria: `Tidak termakan fake, tetap ke QB kalau bola masih di tangannya — 8/10 benar`,
    prereqs: [],
    sortOrder: 70,
  },
  {
    id: 'RSH-A3',
    name: 'Tangan Naik di Detik Terakhir',
    branch: 'defense',
    position: 'rusher',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Menghalangi jalur lempar saat tidak sempat sack — ≥3 pass terganggu per pertandingan`,
    masteryCriteria: `Menghalangi jalur lempar saat tidak sempat sack — ≥3 pass terganggu per pertandingan`,
    prereqs: [],
    sortOrder: 71,
  },
  {
    id: 'RSH-A4',
    name: 'Disguise Blitz',
    branch: 'defense',
    position: 'rusher',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Memberi sinyal di detik terakhir yang sah (≥1 detik sebelum snap) tanpa kena penalti`,
    masteryCriteria: `Memberi sinyal di detik terakhir yang sah (≥1 detik sebelum snap) tanpa kena penalti`,
    prereqs: [],
    sortOrder: 72,
  },
  {
    id: 'RSH-E1',
    name: 'Rush Berbasis Tendensi QB',
    branch: 'defense',
    position: 'rusher',
    tier: 5,
    tierLabel: 'Elite',
    description: `Tahu QB lawan cenderung mundur/geser ke kanan, sesuaikan sudut — success rate naik ≥20%`,
    masteryCriteria: `Tahu QB lawan cenderung mundur/geser ke kanan, sesuaikan sudut — success rate naik ≥20%`,
    prereqs: [],
    sortOrder: 73,
  },
  {
    id: 'RSH-E2',
    name: 'Tahu Kapan Tidak Blitz',
    branch: 'defense',
    position: 'rusher',
    tier: 5,
    tierLabel: 'Elite',
    description: `Blitz = 3 defender lawan 4 receiver. Bisa menjelaskan dan memilih dengan benar 8/10 situasi`,
    masteryCriteria: `Blitz = 3 defender lawan 4 receiver. Bisa menjelaskan dan memilih dengan benar 8/10 situasi`,
    prereqs: [],
    sortOrder: 74,
  },
  {
    id: 'DB-F1',
    name: 'Backpedal',
    branch: 'defense',
    position: 'db',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Punggung lurus, langkah pendek, tanpa berdiri tegak`,
    drill: `Punggung lurus, langkah pendek, tanpa berdiri tegak`,
    masteryCriteria: `Backpedal 15 yard tetap seimbang, 10 kali berturut-turut`,
    prereqs: [],
    sortOrder: 75,
  },
  {
    id: 'DB-F2',
    name: 'Membuka Pinggul & Transisi',
    branch: 'defense',
    position: 'db',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Backpedal → putar → sprint tanpa langkah sia-sia`,
    drill: `Backpedal → putar → sprint tanpa langkah sia-sia`,
    masteryCriteria: `Transisi dalam 1 langkah di 8/10 percobaan`,
    prereqs: [],
    sortOrder: 76,
  },
  {
    id: 'DB-F3',
    name: 'Leverage & Cushion',
    branch: 'defense',
    position: 'db',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Jaga jarak 5–7 yard, posisikan badan sesuai bantuan`,
    drill: `Jaga jarak 5–7 yard, posisikan badan sesuai bantuan`,
    masteryCriteria: `Posisi benar di 9/10 snap`,
    prereqs: [],
    sortOrder: 77,
  },
  {
    id: 'DB-F4',
    name: 'Disiplin Mata',
    branch: 'defense',
    position: 'db',
    tier: 2,
    tierLabel: 'Foundation',
    description: `Man: lihat pinggang receiver. Zone: lihat QB`,
    drill: `Man: lihat pinggang receiver. Zone: lihat QB`,
    masteryCriteria: `Nol kali "tertipu" dalam 10 snap zone`,
    prereqs: [],
    sortOrder: 78,
  },
  {
    id: 'DB-C1',
    name: 'Man Coverage — Mirroring',
    branch: 'defense',
    position: 'db',
    tier: 3,
    tierLabel: 'Core',
    description: `Ikuti pinggang, bukan kepala atau bahu`,
    drill: `Ikuti pinggang, bukan kepala atau bahu`,
    masteryCriteria: `Receiver terbuka ≤3 dari 10 route`,
    prereqs: [],
    sortOrder: 79,
  },
  {
    id: 'DB-C2',
    name: 'Zone Coverage — Landmark',
    branch: 'defense',
    position: 'db',
    tier: 3,
    tierLabel: 'Core',
    description: `Tahu titik jaga, pass off receiver yang keluar zona`,
    drill: `Tahu titik jaga, pass off receiver yang keluar zona`,
    masteryCriteria: `Nol receiver lolos tanpa diserahkan, 10 snap`,
    prereqs: [],
    sortOrder: 80,
  },
  {
    id: 'DB-C3',
    name: 'Break pada Bola',
    branch: 'defense',
    position: 'db',
    tier: 3,
    tierLabel: 'Core',
    description: `Baca lemparan, potong jalur`,
    drill: `Baca lemparan, potong jalur`,
    masteryCriteria: `6/10 sampai ke bola bersamaan receiver`,
    prereqs: [],
    sortOrder: 81,
  },
  {
    id: 'DB-C4',
    name: 'Deflag Segera Setelah Tangkapan',
    branch: 'defense',
    position: 'db',
    tier: 3,
    tierLabel: 'Core',
    description: `Batasi YAC ke 0–2 yard`,
    drill: `Batasi YAC ke 0–2 yard`,
    masteryCriteria: `Rata-rata YAC yang diberikan ≤2 yard`,
    prereqs: [],
    sortOrder: 82,
  },
  {
    id: 'DB-C5',
    name: 'Menghindari Pass Interference',
    branch: 'defense',
    position: 'db',
    tier: 3,
    tierLabel: 'Core',
    description: `10 yard + otomatis first down. Mainkan bola, bukan badan`,
    drill: `10 yard + otomatis first down. Mainkan bola, bukan badan`,
    masteryCriteria: `Nol PI dalam 3 pertandingan`,
    prereqs: [],
    sortOrder: 83,
  },
  {
    id: 'DB-C6',
    name: 'Menghindari Illegal Flag Pull',
    branch: 'defense',
    position: 'db',
    tier: 3,
    tierLabel: 'Core',
    description: `Hanya boleh mencabut flag runner — 5 yard kalau salah`,
    drill: `Hanya boleh mencabut flag runner — 5 yard kalau salah`,
    masteryCriteria: `Nol penalti illegal flag pull`,
    prereqs: [],
    sortOrder: 84,
  },
  {
    id: 'DB-A1',
    name: 'Membaca Kombinasi Route',
    branch: 'defense',
    position: 'db',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Kenali mesh, smash, flood, levels dalam 2 detik — 8/10 benar dari video`,
    masteryCriteria: `Kenali mesh, smash, flood, levels dalam 2 detik — 8/10 benar dari video`,
    prereqs: [],
    sortOrder: 85,
  },
  {
    id: 'DB-A2',
    name: 'Deep Half vs Deep Third',
    branch: 'defense',
    position: 'db',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Tahu bedanya dan tanggung jawabnya di 3-2 vs 1-3-1 — nol big play akibat salah zona`,
    masteryCriteria: `Tahu bedanya dan tanggung jawabnya di 3-2 vs 1-3-1 — nol big play akibat salah zona`,
    prereqs: [],
    sortOrder: 86,
  },
  {
    id: 'DB-A3',
    name: 'Interception',
    branch: 'defense',
    position: 'db',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Tangan tinggi menjemput bola, bukan menunggu di dada — ≥1 INT per 3 pertandingan`,
    masteryCriteria: `Tangan tinggi menjemput bola, bukan menunggu di dada — ≥1 INT per 3 pertandingan`,
    prereqs: [],
    sortOrder: 87,
  },
  {
    id: 'DB-A4',
    name: 'Pertahanan No-Run Zone',
    branch: 'defense',
    position: 'db',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Lari ilegal di sana → semua 5 pemain coverage penuh. Bisa jelaskan dan eksekusi`,
    drill: `Lari ilegal di sana → semua 5 pemain coverage penuh. Bisa jelaskan dan eksekusi`,
    masteryCriteria: `Konversi lawan di no-run zone turun di bawah 40%`,
    prereqs: [],
    sortOrder: 88,
  },
  {
    id: 'DB-A5',
    name: 'Switch & Komunikasi Banjir',
    branch: 'defense',
    position: 'db',
    tier: 4,
    tierLabel: 'Advanced',
    description: `Menangani 2 receiver menyilang di zona yang sama`,
    drill: `Menangani 2 receiver menyilang di zona yang sama`,
    masteryCriteria: `Nol kebingungan dalam 10 snap kombinasi`,
    prereqs: [],
    sortOrder: 89,
  },
  {
    id: 'DB-E1',
    name: 'Memancing QB',
    branch: 'defense',
    position: 'db',
    tier: 5,
    tierLabel: 'Elite',
    description: `Sengaja memberi celah lalu menutupnya — ≥2 INT hasil pancingan per musim`,
    masteryCriteria: `Sengaja memberi celah lalu menutupnya — ≥2 INT hasil pancingan per musim`,
    prereqs: [],
    sortOrder: 90,
  },
  {
    id: 'DB-E2',
    name: 'Pertahanan Sideline & 2 Menit',
    branch: 'defense',
    position: 'db',
    tier: 5,
    tierLabel: 'Elite',
    description: `Paksa lawan ke tengah agar jam terus berjalan — dinilai pelatih dari rekaman`,
    masteryCriteria: `Paksa lawan ke tengah agar jam terus berjalan — dinilai pelatih dari rekaman`,
    prereqs: [],
    sortOrder: 91,
  },
]

export function getSkill(id: string): SkillNode | undefined {
  return SKILLS.find((s) => s.id === id)
}

export function skillsByBranch(branch: SkillBranch): SkillNode[] {
  return SKILLS.filter((s) => s.branch === branch && s.position == null)
}

export function skillsByPosition(position: SkillPosition): SkillNode[] {
  return SKILLS.filter((s) => s.position === position)
}

export function generalSkills(): SkillNode[] {
  return SKILLS.filter((s) => s.branch === 'general')
}
